//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.StateElimination.Transitiongraph
{
    
    
    /// <summary>
    /// The public interface for State
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(State))]
    [XmlDefaultImplementationTypeAttribute(typeof(State))]
    public interface IState : IModelElement
    {
        
        /// <summary>
        /// The id property
        /// </summary>
        int Id
        {
            get;
            set;
        }
        
        /// <summary>
        /// The isFinal property
        /// </summary>
        bool IsFinal
        {
            get;
            set;
        }
        
        /// <summary>
        /// The isInitial property
        /// </summary>
        bool IsInitial
        {
            get;
            set;
        }
        
        /// <summary>
        /// The outgoing property
        /// </summary>
        IOrderedSetExpression<ITransition> Outgoing
        {
            get;
        }
        
        /// <summary>
        /// The incoming property
        /// </summary>
        IOrderedSetExpression<ITransition> Incoming
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Id property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IdChanging;
        
        /// <summary>
        /// Gets fired when the Id property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IdChanged;
        
        /// <summary>
        /// Gets fired before the IsFinal property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsFinalChanging;
        
        /// <summary>
        /// Gets fired when the IsFinal property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsFinalChanged;
        
        /// <summary>
        /// Gets fired before the IsInitial property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsInitialChanging;
        
        /// <summary>
        /// Gets fired when the IsInitial property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsInitialChanged;
    }
}

